### ISSUE TITLE
Disable "categories" taxonomy

### ISSUE THREAD

**Issue by matkv** [matkv/matkv.dev#272]
**Only** that one, not tags in general

**Comment by matkv** [comment]
Currently /categories still works - should throw 404 instead. The option to just set
```toml
[taxonomies]
   tag = "tags"
```

doesn't actually disable categories.
